apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      initContainers:
        - name: ingest-init
          image: "groundnuty/k8s-wait-for"
          args:
            - "job"
            - "ingest-dbmigration-#{Build.BuildNumber}#"
      containers:
        - name: ingest
          image: "#{AcrRegistry}#/#{AcrPath}#:#{Build.BuildNumber}#"
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: "#{DatabaseUrl}#"
            - name: SECRET_KEY_BASE
              value: "#{SecretKeyBase}#"
            - name: PORT
              value: "4000"
            - name: PHX_HOST
              value: "#{Host}#"
            - name: OKTA_ISSUER
              value: "#{Okta.Issuer}#"
            - name: OKTA_CLIENT_ID
              value: "#{Okta.ClientId}#"
            - name: OKTA_CLIENT_SECRET
              value: "#{Okta.ClientSecret}#"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-dbmigration-#{Build.BuildNumber}#
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: ingest-dbmigration
          image: "#{AcrRegistry}#/#{Acr.MigrationPath}#:#{Build.BuildNumber}#"
          env:
            - name: DATABASE_URL
              value: '#{DatabaseUrl}#'
            - name: SECRET_KEY_BASE
              value: "#{SecretKeyBase}#"
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.60.1.7
          - 10.60.1.8
        searches:
          - inel.gov
          - inl.gov
      restartPolicy: Never

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: JobWatcher
rules:
  - apiGroups:
      - ""
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: JobWatcher
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: JobWatcher

---
# 2-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ingest-service
spec:
  selector:
    app: ingest
  ports:
    - port: 80
      targetPort: 4000
      name: http
      protocol: TCP